### ISSUE TITLE
How to use tags to supplement category sorting

### ISSUE THREAD

**Issue by Peterbudolfsen** [ylefebvre/link-library#5]
Hi
I very much like your plugin, which I am currently using to build a links library. 

One question though:
How do I sort by using tags? 

I have links in a number of categories, that I can obviously sort, but I would like to be able to limit the results in a category, to certain tags (english and danish language). 
Is there a way to do this?

www.moneylibrary.dk

Best regards Peter

**Comment by ylefebvre** [comment]
Hi Peter,

The way that tags are currently implemented, they have three purposes

1) You can display them along with other link information
2) You can select the option for tags to be clickable links so that clicking on them would only show links that have that tag.
3) You can use the taglistoverride and taglistoverrideCSV parameters of the link-library shortcode to only show links that belong to the selected tag(s)

Let me know if this helps.

Yannick
