### ISSUE TITLE
Option to ignore beginning article, e.g., "a, an, the", when sorting alphabetically by title

### ISSUE THREAD

**Issue by langlers** [ylefebvre/link-library#7]
I would prefer to ignore any beginning article, e.g., "a, an, the", when sorting alphabetically by title. Wondering if there is a built-in option that I'm overlooking. Otherwise, can you suggest a way of achieving this, perhaps via a hook or filter?

thank you

**Comment by ylefebvre** [comment]
That's a very good question. Link Library uses custom post types and the built-in WP Query class to sort its content. I will need to dig in and see if it's possible to add a hook or filter around this. I will try to tackle this over the holidays.

**Comment by ylefebvre** [comment]
I just pushed version 7.3 Beta 2 on here, which includes a new option to ignore articles. By default, none are ignored as I did not want to change people's sorting order without their knowledge. To ignore articles, go to the Global Options section of Link Library and add the articles in the field labeled "Articles to be ignored when sorting (separate with |)". For example, to ignore the articles you mentioned before, you would enter A|An|The. It is not case-sensitive.

This version has not become the official version in WordPress yet as I've asked beta testers to try it out. This new version introduces another new feature that I wanted to be sure did not break anything. Users can now select to use post categories and tags instead of using the ones that are specific to Link Library. Normally, this should not change anything in people's sites, but I wanted to be sure before pushing this change out.

Let me know if this works and consider donating to support this plugin's development.

**Comment by langlers** [comment]
Awesome! Thank you. I’ll try it out on our staging site and report back if we see any issues.

**Comment by ylefebvre** [comment]
Have you been able to configure the search as desired with the new field? Version 7.3 is now officially released.

**Comment by langlers** [comment]
I finally had a chance to try it out, and things work great if I only enter "the". However, if I use "a|an|the" the results are strange. I've included attachments showing how things are being sorted in each case. In our case, we only need to use "the" so this isn't an issue for us, but I'm happy to help work out any kinks. Let me know if you would like any additional info.

**Example with "a|an|the"**
<img width="1144" alt="Screen Shot 2022-02-09 at 07 55 11" src="https://user-images.githubusercontent.com/10180746/153238633-2a54c49a-79e3-4c9a-a466-0ffd2db6d37b.png">

**Example with only "the"**
<img width="1147" alt="Screen Shot 2022-02-09 at 07 54 33" src="https://user-images.githubusercontent.com/10180746/153238659-8e8e0d19-aa7f-42a9-954f-60df4ea6088b.png">

**Comment by ylefebvre** [comment]
Thanks for the detailed explanation. I have found a better filter function that properly works with multiple article filtering. You can find this fix in version 7.3.2. Let me know if it works better for you as well.

**Comment by langlers** [comment]
Looks to have done the trick! Thanks.

**Comment by ylefebvre** [comment]
Thanks for the confirmation!
